;PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html



[env:esp32_littleFS]
    # # sembra funzionare con AzDelivery ESP32-WROOM 32
    platform = espressif32
    framework = arduino
    board = esp32dev
    # board = esp-wrover-kit
    upload_speed = 460800
    monitor_speed = 115200
    monitor_filters = colorize
    # upload_port = /dev/ttyUSB0
    board_build.filesystem = littlefs

    # build_flags = -g -DDEBUG_FAUXMO=Serial -DDEBUG_FAUXMO_VERBOSE_TCP=0  -DDEBUG_FAUXMO_VERBOSE_UDP=0
    # lib_deps = AsyncTCP

    # ref: https://docs.platformio.org/en/stable/projectconf/sections/env/options/library/lib_ignore.html
    lib_ignore =
        telegram_sample # solo nome del folder sena il path
        @testArea # solo nome del folder sena il path


    # -------------------------------------
    # inserire le librerie esterne o personali da includere nella compilazione
    # considerare che pr i relative path, la base_dir --> same level of src
    # -------------------------------------
    lib_extra_dirs =
        ./lib/extraLibraries
        ./lib/lnLibrary
        # ../lib/extraLibraries
        # ../lib/lnLibrary


    # -------------------------------------
    # ref: https://docs.platformio.org/en/stable/projectconf/sections/env/options/build/build_src_filter.html
    # inserire tutti i percorsi che si desidera inserire nel codice
    # considerare che per i relative path, la base_dir --> src
    # -------------------------------------
    build_src_filter =
        # +<test_pins.cpp>
        +<Source/main.cpp>
        # +<Source/code/pinsInitialization.cpp>
        # +<Source/code/ln_Alexa.cpp>
        # +<Source/code/ln_telegram.cpp>
        # +<Source/code/pressControl.cpp>
        +<Source/code>


    # -------------------------------------
    # ref: https://docs.platformio.org/en/stable/projectconf/sections/env/options/build/build_flags.html
    # inserire gli include file, opzioni per il compilatore
    # considerare che pr i relative path, la base_dir --> same level of src
    # -------------------------------------
    build_flags=
        # -Wall
        # -Wdeprecated-declarations
        -I Source/include
        -I /home/loreto/lnProfile/envars/include # per ssid.h e telegram_bot.h  @ln_ssid_credentials.h



[platformio]
    src_dir = .
    # ref: https://docs.platformio.org/en/latest/projectconf/sections/platformio/options/directory/lib_dir.html
    # default_envs = nodemcu32
    default_envs = esp32_littleFS
    # default_envs = esp32


